version: "3.9"

services:
  tg-svodd-bot:
    image: ${REGISTRY}/tg-svodd-bot:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - registry
    networks:
      - rmq-net
      - tg-bot-net
    environment:
      RABBIT_SERVER_URL: amqp://rmq
      RABBIT_EXCHANGE_NAME: ex1
      TG_CHAT_ID: "@svoddru"
      Q1: rabbit://q1
      TG_BOT_TOKEN_FILE: /run/secrets/tg_bot_token
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
    secrets:
      - tg_bot_token
      - sentry_dsn
    command: './tg-svodd-bot'
    deploy:
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 100
        window: 120s

secrets:
  tg_bot_token:
    file: ${APP_TG_BOT_TOKEN_FILE}
  sentry_dsn:
    file: ${APP_SENTRY_DSN_FILE}

networks:
  rmq-net:
    name: rmq-net
    external: true
  tg-bot-net:
